version: '3.8'

services:
    api:
        build: ./api
        restart: always
        expose:
            - '3000'
        environment:
            PORT: 3000
            DATABASE_URL: postgresql://postgres:postgres_dev@postgres:5432/reiz
            SECRET: ${API_SECRET}
            SALT: ${API_SALT}
            TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
            TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
            CORS_ORIGINS: https://reiz.com.ua
        volumes:
            - ./api/uploads:/usr/src/app/uploads
        depends_on:
            - postgres
        networks:
            - reiz

    web:
        build: 
            context: ./front
            dockerfile: Dockerfile
        image: my-next-app:latest
        environment:
            NODE_ENV: production
            HOSTNAME: 0.0.0.0
            PORT: 8080
        expose:
            - "8080"
        restart: always
        networks:
            - reiz

    postgres:
        image: postgres:16
        restart: always
        expose:
            - '5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: reiz
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres_dev
        networks:
            - reiz
    
    caddy:
        image: caddy:2.7
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - reiz

volumes:
    pgdata:
    caddy_data:
    caddy_config:

networks:
    reiz:
